#!/bin/bash

# Homebrew paths.
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# Android paths
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/emulator
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/tools/bin
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

# Additional man(1) paths.
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Homebrew support.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Silence the bash deprecation warning.
export BASH_SILENCE_DEPRECATION_WARNING=1

SHELL_SESSION_HISTORY=0
