#!/bin/bash
# airplane
# aoneill - 11/27/15

function _lid() {
  local cur prev
  opts='ignore poweroff reboot halt kexec suspend hibernate hybrid-sleep lock'

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}

  if [[ "$COMP_CWORD" == "1" ]]
  then
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    return 0
  fi
}
complete -F _lid lid
