#!/bin/bash
# internet
# aoneill - 08/18/16

VISUAL=0
[[ "$#" == "1" ]] && [[ "$1" == "-v" || "$1" == "--visual" ]] && VISUAL="1"

timeout 0.5 curl --silent --head http://www.google.com/ \
  | grep -q "HTTP/[0-9]\+\.[0-9]\+ [2-3]0[0-9]"
status="$?"

(( VISUAL )) && echo "$status"
(( ! VISUAL )) && exit "$status"
