#!/bin/bash
# 20-alias
# aoneill - 11/26/15

# Aliases
alias sudo="sudo -E"

# Sudo shortcuts
alias airplane="sudo airplane"
alias amount="sudo amount"
alias aumount="sudo aumount"
alias journalctl="sudo journalctl"
alias lid="sudo lid"
alias pacman="sudo pacman"
alias pacro="sudo pacro"
alias roam="sudo roam"
alias systemctl="sudo systemctl"
alias wifi-menu="sudo wifi-menu"
alias wpa-scan="sudo wpa-scan"

# Replacement
alias make="makeup"

# Mapping
alias cls="clear"
alias g="git"
alias ipy="ipython"
alias lock="sxlock"
alias net="nmcli"
alias open="xdg-open"
alias py="python"
alias py2="python2"
alias sml="rlwrap sml"
alias vi="vim"

# Mapping with flags
alias dhcp="sudo dhcpcd -k; sudo dhcpcd -n"
alias ls="ls -v --color"
alias l="ls -a"
alias la="ls -la"
alias ll="ls -l"
alias pacaur="pacaur --aur"
alias perms="stat -c '%a %n'"
alias psgrep="ps aux | grep"
alias csim="sim -no-gui -no-win"
alias vdiff='diff --width=$(tput cols) -y'
alias reload-udev="sudo udevadm control --reload-rules"
alias i3-restart="i3-msg restart"
