#!/bin/bash
# 20-alias
# aoneill - 11/26/15

# Aliases
alias sudo="sudo -E"

# Sudo shortcuts
alias airplane="sudo airplane"
alias amount="sudo amount"
alias aumount="sudo aumount"
alias journalctl="sudo journalctl"
alias lid="sudo lid"
alias netctl-auto="sudo netctl-auto"
alias netctl-restart="sudo netctl-restart"
alias pacman="sudo pacman"
alias pacro="sudo pacro"
alias roam="sudo roam"
alias systemctl="sudo systemctl"
alias wifi-menu="sudo wifi-menu"
alias wpa-scan="sudo wpa-scan"

# Replacement
alias python="ipython"
alias make="makeup"

# Mapping
alias cls="clear"
alias g="git"
alias lock="sxlock"
alias net="netctl-auto"
alias open="xdg-open"
alias py="python"
alias sml="rlwrap sml"
alias vi="vim"

# Mapping with flags
alias dhcp="sudo dhcpcd -k; sudo dhcpcd -n"
alias ls="ls --color"
alias l="ls -a"
alias la="ls -la"
alias ll="ls -l"
alias pacaur="pacaur --aur"
alias perms="stat -c '%a %n'"
alias psgrep="ps aux | grep"
alias csim="sim -no-gui -no-win"
alias vdiff='diff --width=$(tput cols) -y'
alias reload-udev="sudo udevadm control --reload-rules"
alias i3-restart="i3-msg restart"

## Shortcuts
alias gst="git st"
alias gstat="gst"
alias st="gst"
alias pending="gst"
alias p="gst"

alias gci="git ci"
alias gcommit="gci"
alias ci="gci"

alias gbr="git br"
alias gbranch="gbr"
alias br="gbr"

alias gco="git co"
alias gcheckout="gco"
alias co="gco"

alias gdiff="git diff"

alias gph="git push"
alias gpush="gph"
alias push="gph"
