#!/bin/bash
# 80-prompt
# aoneill - 11/26/15

function prompt_command {
  OLD_PWD_BACKUP="$OLD_PWD"
  HOST="\[${BLD_GRN}\]\u@\h\[${TXT_RST}\]"

  git branch &>/dev/null;
  if [ "$?" -eq 0 ]
  then
    git status 2>/dev/null | grep "nothing to commit" &>/dev/null;

    # Changed files
    if [ "$?" -eq "0" ]; then
      git cherry -v 2>/dev/null | grep "+" &>/dev/null;

      # Uncommitted Changes
      if [ "$?" -eq "0" ]; then
        GIT=$BLD_PUR
      else
        GIT=$BLD_CYN
      fi
    else
      GIT=$BLD_RED
    fi

    # Git base dir
    git="$(git rev-parse --show-toplevel 2>/dev/null)"
    if [[ "$git" == "/" ]]; then
      DIR="\[${BLD_BLU}\]\w\[${TXT_RST}\]"
    else
      # Path to Git folder
      gitPath="$(pwd | sed "s|$(dirname "$git")||")"
      git="$(dirname "$git" | sed "s|^$HOME|~|")"

      # Color accordingly
      DIR="\[${BLD_BLU}\]$git\[${GIT}\]$gitPath\[${TXT_RST}\]"
    fi
  else
    DIR="\[${BLD_BLU}\]\w\[${TXT_RST}\]"
  fi

  # Export proper coloring
  PS1="${HOST}:${DIR}$ "

  # Save history
  history -a

  # Restore old pwd
  OLD_PWD="$OLD_PWD_BACKUP"
}

PROMPT_COMMAND=prompt_command
