#!/bin/bash
# 81-preexec
# aoneill - 12/20/15

# Command run before input command
function prexec_command {
  # Save history
  history -a
}

# Wrapper for ease of use
# http://superuser.com/questions/175799/does-bash-have-a-hook-that-is-run-before-executing-a-command
preexec_invoke_exec () {
  # Do nothing if completing
  [ -n "$COMP_LINE" ] && return
  
  # Don't cause a preexec for $PROMPT_COMMAND
  [ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && return

  local this_command=`HISTTIMEFORMAT= history 1 | sed -e "s/^[ ]*[0-9]*[ ]*//"`;
  prexec_command "$this_command"
}
trap 'preexec_invoke_exec' DEBUG
