#!/bin/bash
# 91-welcome
# aoneill - 11/26/15

# Printing drive statistics
# Laptop
hostname | grep "Laptop" > /dev/null
if [ $? -eq 0 ]; then
  printDriveStats /dev/sda3 SSD
fi

# Desktop
hostname | grep "Desktop" > /dev/null
if [ $? -eq 0 ]; then
  printDriveStats /dev/sda2 SDD
  printDriveStats /dev/sdb2 HDD
fi

# Notify about unsaved changes
if env-diff --quiet; then
  echo -e "\n${BLD_RED}WARNING${TXT_RST}: Uncommitted changes in ~/.env/git"
  echo -e "Update with \`env-push'"
fi
