#!/bin/bash
# 91-welcome
# aoneill - 11/26/15

! [ -t 0 ] && return;

# Printing drive statistics
# Laptop
hostname | grep "Laptop" > /dev/null
if [ $? -eq 0 ]; then
  printDriveStats /dev/sda3 SSD
fi

# Desktop
hostname | grep "Desktop" > /dev/null
if [ $? -eq 0 ]; then
  printDriveStats /dev/sda2 SDD
  printDriveStats /dev/sdb2 HDD
fi

# Try to pull updates
if env-status --pull; then
  echo -e "${BLD_GRN}Environment${TXT_RST}: Updating..."
  env-pull
fi

# Notify about unsaved changes
if env-status --push; then
  echo -e "\n${BLD_RED}WARNING${TXT_RST}: Uncommitted changes in ~/.env/git"
  echo -e "Update with \`env-push'"
fi
